replies:
  #æ–‡æœ¬ç±»å‹çš„å›å¤
  - type: text
    rules:
      - åœ¨å—
      - æ»´æ»´
      - didi
      - æœºå™¨äºº 
    content: æˆ‘åœ¨å“¦ï¼
  - type: text
    rules:
      - æ»š
      - å»ä½ å¦ˆ
    content: ğŸ¤¬
  - type: text
    rules:
      - ç‰›
      - ğŸ®
    content: ç‰›å•ŠğŸ®



  - type: text
    rules:
      - æˆ‘æ˜¯
      - ç¾¤èŠ
      - æ·»åŠ 
      - è¯·æ±‚
    content: å¦‚éœ€ä¸Šè½¦æˆ–è€…ç»‘å®šæœºå™¨äººè¯·è”ç³»ç®¡ç†å‘˜ï¼Œå‘é€ä¸Šè½¦è·å–è¯¦æƒ…

  - type: url
    rules:
      - åŠŸèƒ½
      - èœå•
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://github.com/LJMX996/jd/raw/aaron/sillyGirl/caidan.txt
#å°çˆ±æœºå™¨äºº 
  - type: url
    rules:
      - (\S*)
    request:
      response_type: json
      url: http://www.tuling123.com/openapi/api?key=4670f9d766704929b7983312808cdfa7&userid=xiaoxiao&info={{1}}
      get: text
#å°çˆ±æœºå™¨äºº 
  - type: url
    rules:
      - å–µå–µ(\S*)
      - é˜¿å¡ä¸½(\S*)
    request:
      response_type: json
      url: http://www.tuling123.com/openapi/api?key=4670f9d766704929b7983312808cdfa7&userid=xiaoxiao&info={{1}}
      get: text

  - type: url
    rules:
      - å¤–å–
      - ç¾å›¢
      - é¥¿äº†
      - åƒé¥­
      - é¥¿
      - æ°é¥­
      - çº¢åŒ…
    request:
      response_type: image
      url: 'https://i.loli.net/2021/12/03/MS4LKzTyd5WCc1X.jpg'

  - type: url
    rules:
      - é»„å†
    request:
      response_type: text
      url: http://81.70.100.130/api/huang.php

  - type: url
    rules:
      - ä»Šæ—¥è¦é—»
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://api.muuzi.cn/api/60look

  - type: url
    rules:
      - ä¸–ç•Œæ–°é—»
      - ä¸€åˆ†é’Ÿçœ‹ä¸–ç•Œ
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.2xb.cn/zaob
        get: imageUrl









  - type: url
    rules:
      - (.*)å¤©æ°”
      - å¤©æ°”(.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/tq.php?msg={{1}}&n=1

  - type: url
    rules:
      - æœªæ¥ä¸‰å¤© (.*)
      - (.*) æœªæ¥ä¸‰å¤©
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/tq.php?msg={{1}}

  - type: url
    rules:
      - åœ°ç†ä½ç½® (.*)
      - (.*) åœ°ç†ä½ç½®
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/location_address_geocoder.php?address={{1}}

  - type: url
    rules:
      - èº«ä»½è¯ (.*)
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/sfz.php?msg={{1}}

  - type: url
    rules:
      - æ‰‹æœºå·æŸ¥è¯¢ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.2xb.cn/phone?tel={{1}}


 

 
  - type: url
    rules:
      - äºŒç»´ç  (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: image
        url: https://api.qrserver.com/v1/create-qr-code/?size=150Ã—150&data={{1}}
      
  - type: url
    rules:
      - ç½‘æ˜“äº‘çƒ­è¯„
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/comments.163?format=text




  - type: url
    rules:
      - åœŸå‘³
      - åœŸå‘³æƒ…è¯
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.qinghua?format=text

  - type: url
    rules:
      - èˆ”ç‹—æ—¥è®°
      - èˆ”ç‹—
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.oick.cn/dog/api.php

  - type: url
    rules:
      - ç‹—å±ä¸é€šæ–‡ç« ç”Ÿæˆ (.*)
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/dog.php?msg={{1}}&num=257

  #å†å²ä¸Šçš„ä»Šå¤©
  - type: url
    rules:
      - å†å²ä¸Šçš„ä»Šå¤©
    request:
      url: 'https://api.iyk0.com/lishi/'
      response_type: template
      template: "fjson(tfmt(01æœˆ02æ—¥).[i],[i]. [?.year]ï¼Œ[?.title]ã€‚,\n)"


  - type: url
    rules:
      - è¡¨ç™½ç½‘é¡µ
    content: http://81.70.100.130/api/biaobai/biaobai.php?a=ç¾¤ä¸»çˆ¸çˆ¸
    

  - type: text
    rules:
      - ä¸‰åˆä¸€æ”¶æ¬¾ç 
    content: http://81.70.100.130/api/skm/api.php?biaoti=æ ‡é¢˜&touxiang=QQå·&nicheng=æ”¶æ¬¾äººæ˜µç§°&qq=QQæ”¶æ¬¾ç é“¾æ¥&vx=å¾®ä¿¡æ”¶æ¬¾ç é“¾æ¥&zfb=æ”¯ä»˜å®æ”¶æ¬¾ç é“¾æ¥

  - type: url
    rules:
      - æ—©å®‰
      - æ™šå®‰
      - åˆå®‰
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://xiaobai.klizi.cn/API/getImage-master/out_image.php



  - type: url
    rules:
      - MCé…±
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/McImg.php

  - type: url
    rules:
      - æ¼«å›¾
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1?sort=åŠ¨æ¼«&format=images






  - type: url
    rules:
      - äºŒæ¬¡å…ƒ1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://acg.toubiec.cn/random.php





  - type: url
    rules:
      - äºŒæ¬¡å…ƒ2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2?sort=äºŒæ¬¡å…ƒ&format=images

  - type: url
    rules:
      - äºŒæ¬¡å…ƒ3
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1?sort=äºŒæ¬¡å…ƒ&format=images

  - type: url
    rules:
      - ç¾å›¾è¯±æƒ‘
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'





  - type: url
    rules:
      - cosç¾å›¾
    request:
      response_type: image
      url: 'https://api.iyk0.com/cos'

  #å¿…åº”ç¾å›¾
  - type: url
    rules:
      - bingç¾å›¾
    request:
      response_type: image
      url: 'https://api.iyk0.com/bing'


  - type: url
    rules:
      - ä¹°å®¶ç§€
    request:
      response_type: image
      url: 'https://api.iyk0.com/mjx'

  - type: url
    rules:
      - ç§€å„¿
    request:
        #å›¾ç‰‡
        response_type: image 
        url: 'https://api.uomg.com/api/rand.img3?sort=èƒ–æ¬¡çŒ«&format=images'


  - type: url
    rules:
      - å¦¹å­
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2?sort=ç¾å¥³&format=images





  - type: url
    rules:
      - å¦¹å¦¹
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://cdn.seovx.com/?mom=302





  - type: url
    rules:
      - æ‰‹æœºå£çº¸1
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'



  - type: url
    rules:
      - éšæœº1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2&format=images

  - type: url
    rules:
      - éšæœº2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1&format=images

  - type: url
    rules:
      - å¤´åƒç”·
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.avatar?sort=åŠ¨æ¼«ç”·&format=images

  - type: url
    rules:
      - å¤´åƒå¥³
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.avatar?sort=åŠ¨æ¼«å¥³&format=images

  - type: url
    rules:
      -  ä¸¾ç‰Œ(.*)
    request:
      response_type: image
      url: http://xiaobai.klizi.cn/API/tw/source.php?text={{1}}

  - type: url
    rules:
      - æ¶©å›¾
    request:
      response_type: image
      url: 'https://px2.rainchan.win/random'


  - type: url
    rules:
      - è‰²å›¾
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/'
      get: data.url.[0]

  - type: url
    rules:
      - ç‘ŸåœŸ
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/?r18=true'
      get: data.url.[0]

  - type: url
    rules:
      - 10å¼ åœŸ
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/?r18=true&num=10'
      get: data.url.[0]
      

      


  - type: url
    rules:
      - ç¿»è¯‘ (.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/fy.php?msg={{1}}


  - type: text
    rules:
      - å¼ºåˆ¶åŠ ç¾¤
    content: https://api.uomg.com/api/qq.joingroup?qid=ç¾¤å·
    

  - type: text
    rules:
      - å¼ºåˆ¶å¯¹è¯
    content: https://api.uomg.com/api/qq.talk?qq=QQå·ç 


