replies:
  #æ–‡æœ¬ç±»å‹çš„å›å¤
  - type: text
    rules:
      - åœ¨å—
      - æœºå™¨äºº
      - é˜¿å¡ä¸½
      - æ»´æ»´
    content: æˆ‘æ˜¯ä½ çš„ä¸“å±å®è´ï¼Œå¿«æ¥æ’©æˆ‘å§ã€‚å‘é€èœå•è·å–åŠŸèƒ½è¯¦æƒ…ã€‚å¯¹è¯æ—¶å‘é€å°çˆ±å‰ç¼€å°±å¯ä»¥å’Œæˆ‘çš„å°çˆ±å¯¹è¯äº†ã€‚ç”¨æœºå™¨äººç™»é™†åªæ˜¯æŸ¥è¯¢å“¦ï¼æŒ‚è±†éœ€è¦ç‚¹è¿›é“¾æ¥è‡ªå·±ä¸Šè½¦ï¼Œå‘é€ä¸Šè½¦è·å–ä¸Šè½¦é“¾æ¥ã€‚
  - type: text
    rules:
      - æ»š
      - å»ä½ å¦ˆ
    content: ğŸ¤¬
  - type: text
    rules:
      - ç‰›
      - ğŸ®
    content: ç‰›å•ŠğŸ®

  - type: text
    rules:
      - ä¸Šè½¦
      - æœ‰è½¦å—
      - æœ‰è½¦ä¸Šå—
    content: http://47.100.44.200:9999

  - type: url
    rules:
      - åŠŸèƒ½
      - èœå•
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://github.com/LJMX996/jd/raw/aaron/sillyGirl/caidan.txt
#å°çˆ±æœºå™¨äºº 
  - type: url
    rules:
      - (\S*)ï¼Ÿ
    request:
      response_type: json
      url: http://jiuli.xiaoapi.cn/i/xiaoai_tts.php?msg={{1}}
      get: text
#å°çˆ±æœºå™¨äºº 
  - type: url
    rules:
      - å–µå–µ(\S*)
      - é˜¿å¡ä¸½(\S*)
    request:
      response_type: json
      url: http://www.tuling123.com/openapi/api?key=4670f9d766704929b7983312808cdfa7&userid=xiaoxiao&info={{1}}
      get: text

  - type: url
    rules:
      - å¤–å–
      - ç¾å›¢
      - é¥¿äº†
      - åƒé¥­
      - é¥¿
      - æ°é¥­
      - çº¢åŒ…
    request:
      response_type: image
      url: 'https://i.loli.net/2021/12/03/MS4LKzTyd5WCc1X.jpg'

  - type: url
    rules:
      - é»„å†
    request:
      response_type: text
      url: http://81.70.100.130/api/huang.php

  - type: url
    rules:
      - ä»Šæ—¥è¦é—»
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://api.muuzi.cn/api/60look

  - type: url
    rules:
      - ä¸–ç•Œæ–°é—»
      - ä¸€åˆ†é’Ÿçœ‹ä¸–ç•Œ
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.2xb.cn/zaob
        get: imageUrl

  - type: url
    rules:
      - éŸ³ä¹ (.*)
    request:
      response_type: text
      url: 'http://xiaoapi.cn/api/yy.php?type=qq&msg={{1}}&n=1'
      
  - type: url
    rules:
      - æœæ­Œ (.*)(.*)
      - å¬æ­Œ (.*) (.*)
    request:
      response_type: text
      url: https://api.womc.cn/api/qqyy/api.php?msg={{1}}&n={{2}}
      
  - type: url
    rules:
      - çƒ­æ­Œæ¦œ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.music?sort=çƒ­æ­Œæ¦œ&format=json

  - type: url
    rules:
      - æ–°æ­Œæ¦œ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.music?sort=æ–°æ­Œæ¦œ&format=json

  - type: url
    rules:
      - æŠ–éŸ³æ¦œ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.music?sort=æŠ–éŸ³æ¦œ&format=json

  - type: url
    rules:
      - é£™å‡æ¦œ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.music?sort=é£™å‡æ¦œ&format=json

  - type: url
    rules:
      - åŠ¨æ¼« (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/age.php?msg={{1}}&max=10&n=1

  - type: url
    rules:
      - æœå½±ç‰‡ (.*)(.*)
      - çœ‹å½±ç‰‡ (.*) (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/video_so.php?msg={{1}}&max=10&n={{2}}

  - type: text
    rules:
      - è§†é¢‘app
      - è½¯ä»¶
      - çœ‹è§†é¢‘çš„
    content: https://iosfans.cn/appstore/filmapp.html


  - type: url
    rules:
      - (.*)å¤©æ°”
      - å¤©æ°”(.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/tq.php?msg={{1}}&n=1

  - type: url
    rules:
      - æœªæ¥ä¸‰å¤© (.*)
      - (.*) æœªæ¥ä¸‰å¤©
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/tq.php?msg={{1}}

  - type: url
    rules:
      - åœ°ç†ä½ç½® (.*)
      - (.*) åœ°ç†ä½ç½®
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/location_address_geocoder.php?address={{1}}

  - type: url
    rules:
      - èº«ä»½è¯ (.*)
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/sfz.php?msg={{1}}

  - type: url
    rules:
      - æ‰‹æœºå·æŸ¥è¯¢ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.2xb.cn/phone?tel={{1}}

  - type: url
    rules:
      - ipæŸ¥è¯¢ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.2xb.cn/ipquery?ip={{1}}



  - type: url
    rules:
      - è‰ºæœ¯ç­¾å (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/ysqm?type=json&txt=kaq&name={{1}}
 
  - type: url
    rules:
      - çŸ­ç½‘å€ (.*)
      - çŸ­é“¾æ¥ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: https://www.lzfh.com/api/dwz.php?cb=1&sturl=6&longurl={{1}}
        get: dwz_url   
 
  - type: url
    rules:
      - äºŒç»´ç  (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: image
        url: https://api.womc.cn/api/qrcode/api.php?text={{1}}
      
  - type: url
    rules:
      - ç½‘æ˜“äº‘çƒ­è¯„
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/comments.163?format=text


  - type: url
    rules:
      - æ¯’é¸¡æ±¤
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/djt?encode=text

  - type: url
    rules:
      - é¸¡æ±¤
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/yan?encode=text

  - type: url
    rules:
      - éªšè¯
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/saohua?encode=text

  - type: url
    rules:
      - æˆ‘åœ¨äººé—´å‡‘æ•°çš„æ—¥å­
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/zrj?format=text

  - type: url
    rules:
      - åœŸå‘³
      - åœŸå‘³æƒ…è¯
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.uomg.com/api/rand.qinghua?format=text

  - type: url
    rules:
      - èˆ”ç‹—æ—¥è®°
      - èˆ”ç‹—
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.oick.cn/dog/api.php

  - type: url
    rules:
      - ç‹—å±ä¸é€šæ–‡ç« ç”Ÿæˆ (.*)
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/dog.php?msg={{1}}&num=257

  #å†å²ä¸Šçš„ä»Šå¤©
  - type: url
    rules:
      - å†å²ä¸Šçš„ä»Šå¤©
    request:
      url: 'https://api.iyk0.com/lishi/'
      response_type: template
      template: "fjson(tfmt(01æœˆ02æ—¥).[i],[i]. [?.year]ï¼Œ[?.title]ã€‚,\n)"


  - type: url
    rules:
      - è¡¨ç™½ç½‘é¡µ
    content: http://81.70.100.130/api/biaobai/biaobai.php?a=ç¾¤ä¸»çˆ¸çˆ¸
    

  - type: text
    rules:
      - ä¸‰åˆä¸€æ”¶æ¬¾ç 
    content: http://81.70.100.130/api/skm/api.php?biaoti=æ ‡é¢˜&touxiang=QQå·&nicheng=æ”¶æ¬¾äººæ˜µç§°&qq=QQæ”¶æ¬¾ç é“¾æ¥&vx=å¾®ä¿¡æ”¶æ¬¾ç é“¾æ¥&zfb=æ”¯ä»˜å®æ”¶æ¬¾ç é“¾æ¥

  - type: url
    rules:
      - æ—©å®‰
      - æ™šå®‰
      - åˆå®‰
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://xiaobai.klizi.cn/API/getImage-master/out_image.php

  - type: url
    rules:
      - æ—¥å†
    request:
      response_type: image
      url: 'https://api.kbapi.cc/rl.api'

  - type: url
    rules:
      - MCé…±
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/McImg.php

  - type: url
    rules:
      - æ¼«å›¾1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1?sort=åŠ¨æ¼«&format=images


  - type: url
    rules:
      - æ¼«å›¾2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/DmImgS.php



  - type: url
    rules:
      - äºŒæ¬¡å…ƒ1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://acg.toubiec.cn/random.php

  - type: url
    rules:
      - äºŒæ¬¡å…ƒ2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/DmImg.php


  - type: url
    rules:
      - äºŒæ¬¡å…ƒ3
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/acgimg.php

  - type: url
    rules:
      - äºŒæ¬¡å…ƒ4
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2?sort=äºŒæ¬¡å…ƒ&format=images

  - type: url
    rules:
      - äºŒæ¬¡å…ƒ5
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1?sort=äºŒæ¬¡å…ƒ&format=images

  - type: url
    rules:
      - ç¾å›¾è¯±æƒ‘1
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'

  - type: url
    rules:
      - ç¾å›¾è¯±æƒ‘2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/youhuotu.php



  - type: url
    rules:
      - cosç¾å›¾
    request:
      response_type: image
      url: 'https://api.iyk0.com/cos'

  #å¿…åº”ç¾å›¾
  - type: url
    rules:
      - bingç¾å›¾
    request:
      response_type: image
      url: 'https://api.iyk0.com/bing'


  - type: url
    rules:
      - ä¹°å®¶ç§€
    request:
      response_type: image
      url: 'https://api.iyk0.com/mjx'

  - type: url
    rules:
      - ç§€å„¿
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img3?sort=èƒ–æ¬¡çŒ«&format=images


  - type: url
    rules:
      - å¦¹å­1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2?sort=ç¾å¥³&format=images

  - type: url
    rules:
      - å¦¹å­2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1?sort=ç¾å¥³&format=images


  - type: url
    rules:
      - å¦¹å­3
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/pcmnt.php

  - type: url
    rules:
      - å°å§å§
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.nmb.show/xiaojiejie2.php

  - type: url
    rules:
      - å§å§
      - æ¢ä¸€ä¸ª
      - æ¢ä¸ª
      - å†æ¢
      - æ¥ç€æ¢
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/MvImg.php

  - type: url
    rules:
      - å¦¹å¦¹
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://cdn.seovx.com/?mom=302

  - type: url
    rules:
      - ç¾è…¿
    request:
      response_type: image
      url: 'https://api.iyk0.com/mtt'

  - type: url
    rules:
      - è…¿æ§
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2?sort=è…¿æ§&format=images

  - type: url
    rules:
      - å¤§ä¸è¢œ
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.iyk0.com/mtt

  - type: url
    rules:
      - é£æ™¯å›¾
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/view.php

  - type: url
    rules:
      - ç”µè„‘å£çº¸
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/girl.php

  - type: url
    rules:
      - æ‰‹æœºå£çº¸1
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'

  - type: url
    rules:
      - æ‰‹æœºå£çº¸2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/mobil.girl.php

  - type: url
    rules:
      - è”ç›Ÿ
      - LOL
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://81.70.100.130/api/lolskin.php

  - type: url
    rules:
      - éšæœº1
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img2&format=images

  - type: url
    rules:
      - éšæœº2
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img1&format=images

  - type: url
    rules:
      - å¤´åƒç”·
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.avatar?sort=åŠ¨æ¼«ç”·&format=images

  - type: url
    rules:
      - å¤´åƒå¥³
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.avatar?sort=åŠ¨æ¼«å¥³&format=images

  - type: url
    rules:
      -  ä¸¾ç‰Œ(.*)
    request:
      response_type: image
      url: http://xiaobai.klizi.cn/API/tw/source.php?text={{1}}

  - type: url
    rules:
      - æ¶©å›¾
    request:
      response_type: image
      url: 'https://pximg2.rainchan.win/rawimg'


  - type: url
    rules:
      - è‰²å›¾
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/'
      get: data.url.[0]

  - type: url
    rules:
      - ç‘ŸåœŸ
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/?r18=true'
      get: data.url.[0]

  - type: url
    rules:
      - 10å¼ åœŸ
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/?r18=true&num=10'
      get: data.url.[0]
      
  - type: url
    rules:
      - ç²¾é€‰çŸ­è§†é¢‘1
    request:
      response_type: text
      url: http://81.70.100.130/api/jiepai.php
      

  - type: url
    rules:
      - ç²¾é€‰çŸ­è§†é¢‘2
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://api.muuzi.cn/api/yysp?type=txt


#è¾“ç½‘çº¢ã€æ˜æ˜Ÿã€çƒ­èˆã€é£æ™¯ã€æ¸¸æˆã€åŠ¨ç‰©ã€‚
  - type: url
    rules:
      - çŸ­è§†é¢‘ (.*)
      - (.*) çŸ­è§†é¢‘
    request:
        #å›¾ç‰‡
        response_type: text 
        url: http://81.70.100.130/api/jingxuanshipin.php?type={{1}}




  - type: url
    rules:
      - ç™¾ç§‘ (.*)
      - ç™¾åº¦ç™¾ç§‘ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://xiaoapi.cn/api/sgbaike.php?msg={{1}}
        get: data.url

  - type: url
    rules:
      - ç¿»è¯‘ (.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/fy.php?msg={{1}}

  - type: url
    rules:
      - æ”¶å½•æŸ¥è¯¢ (.*)
      - ç™¾åº¦æ”¶å½• (.*)
    request:
      response_type: json
      url: https://api.womc.cn/api/shoulu/api.php?domain={{1}}
      get: data
  - type: url
    rules:
      - ^æŸ¥å­—\s*(\S*)$
    replace:
      - 
        - <br>

        - "\n" 
    request:
        response_type: template
        url: https://api.tianapi.com/txapi/xhzd/index?key=19eea766886493ecd04e770d0c2b56f9&word={{1}}
        template: "æ±‰å­—ï¼šgjson(newslist.[0].hanzi)\nè¯»éŸ³ï¼šgjson(newslist.[0].pyyb)\nè§£é‡Šï¼šgjson(newslist.[0].content)\næ‹“å±•ï¼šgjson(newslist.[0].explain)"    


  - type: url
    rules:
      - åƒåœ¾ (.*)
      - åƒåœ¾åˆ†ç±» (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://xiaoapi.cn/api/laji.php?msg={{1}}

  - type: text
    rules:
      - å¼ºåˆ¶åŠ ç¾¤
    content: https://api.uomg.com/api/qq.joingroup?qid=ç¾¤å·
    

  - type: text
    rules:
      - å¼ºåˆ¶å¯¹è¯
    content: https://api.uomg.com/api/qq.talk?qq=QQå·ç 
        
  - type: url
      - è‚¡ç¥¨ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://zyzcfa.com:444/api/stocks?keyword={{1}}

  - type: url
    rules:
      - ç‹è€…(.*)
      - ç‹è€…è£è€€(.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/wzry.php?msg={{1}}



  - type: url
    rules:
      - ping (.*)
      - è¶…çº§ping (.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/sping.php?url={{1}}

  - type: url
    rules:
      - æˆ˜åŠ› (.*)
      - æœ€ä½æˆ˜åŠ› (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/wzry_zdzl.php?name={{1}}

  - type: url
    rules:
      - æ¸¸æˆ
      - å¼€å§‹æ¸¸æˆ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=å¼€å§‹æ¸¸æˆ

  - type: url
    rules:
      - ç­” (.*)
      - ç­”(.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=ç­”{{1}}

  - type: url
    rules:
      - æç¤º
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=æç¤º




