replies:
  #æ–‡æœ¬ç±»å‹çš„å›å¤
  - type: text
    rules:
      - åœ¨å—
      - å‘¼å«æœºå™¨äºº
      - æœºå™¨äºº
      - ç« æ³½å¤©
      - åˆ˜å¼ºä¸œ
    content: æˆ‘æ˜¯ç« æ³½å¤©ï¼Œæ¬¢è¿æ¥æ’©ï¼Œå–µå–µå–µï¼
  - type: text
    rules:
      - æ»š
      - å»ä½ å¦ˆ
    content: ğŸ¤¬
  - type: text
    rules:
      - ç‰›
      - ğŸ®
    content: ç‰›å•ŠğŸ®

  - type: url
    rules:
      - å§å§
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://api.btstu.cn/sjbz/zsy.php
  
  #ç¾å¥³
  - type: url
    rules:
      - ^ç¾å¥³$
    request:
      response_type: image
      url: 'http://api.btstu.cn/sjbz/zsy.php'
      
  - type: url
    rules:
      - ^å£çº¸$
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'

  #ç¾å›¾è¯±æƒ‘
  - type: url
    rules:
      - ^ç¾å›¾è¯±æƒ‘$
    request:
      response_type: image
      url: 'https://api.iyk0.com/sjmn'

  #COSç¾å›¾
  - type: url
    rules:
      - ^cosç¾å›¾$
    request:
      response_type: image
      url: 'https://api.iyk0.com/cos'

  #å¿…åº”ç¾å›¾
  - type: url
    rules:
      - ^bingç¾å›¾$
    request:
      response_type: image
      url: 'https://api.iyk0.com/bing'

  #æ¶©å›¾
  - type: url
    rules:
      - ^æ¶©å›¾$
    request:
      response_type: image
      url: 'https://pximg2.rainchan.win/rawimg'

  #ä¹°å®¶ç§€
  - type: url
    rules:
      - ä¹°å®¶ç§€
    request:
      response_type: image
      url: 'https://api.iyk0.com/mjx'

  #ç¾è…¿
  - type: url
    rules:
      - ^ç¾è…¿$
    request:
      response_type: image
      url: 'https://api.iyk0.com/mtt'
     #url: 'https://jintia.jintias.cn/api/tk.php'

  #éšæœºè‰²å›¾
  - type: url
    rules:
      - ^è‰²å›¾$
    request:
      response_type: image
      url: 'https://api.nyan.xyz/httpapi/sexphoto/'
      get: data.url.[0]
      
  - type: url
    rules:
      - æ—¥å†
    request:
      response_type: image
      url: 'https://api.kbapi.cc/rl.api'
    

#################### æ–‡å­—ç±» ####################

  #å†å²ä¸Šçš„ä»Šå¤©
  - type: url
    rules:
      - ^å†å²ä¸Šçš„ä»Šå¤©$
    request:
      url: 'https://api.iyk0.com/lishi/'
      response_type: template
      template: "fjson(tfmt(01æœˆ02æ—¥).[i],[i]. [?.year]ï¼Œ[?.title]ã€‚,\n)"

  #QQéŸ³ä¹
  - type: url
    rules:
      - éŸ³ä¹ (.*)
    request:
      response_type: text
      url: 'http://xiaoapi.cn/api/yy.php?type=qq&msg={{1}}&n=1'

  #é“¾æ¥ç±»å‹å›å¤
  - type: url
    rules:
      - äºŒæ¬¡å…ƒ
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://acg.toubiec.cn/random.php

    rules:
      - ä¸–ç•Œæ–°é—»
      - ä»Šæ—¥è¦é—»
      - ä¸€åˆ†é’Ÿçœ‹ä¸–ç•Œ
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.2xb.cn/zaob
        get: imageUrl
        

  - type: url
    rules:
      - å§å§
      - å¦¹å¦¹
      - å°å§å§
    request:
        #å›¾ç‰‡
        response_type: image 
        url: http://api.btstu.cn/sjbz/zsy.php

  - type: url
    rules:
      - æ—©å®‰
      - æ™šå®‰
      - åˆå®‰
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://xiaobai.klizi.cn/API/getImage-master/out_image.php

  - type: url
    rules:
      - ä¹°å®¶ç§€
      - ç§€å„¿
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.uomg.com/api/rand.img3?sort=èƒ–æ¬¡çŒ«&format=image

  - type: url
    rules:
      - æ¢ä¸€ä¸ª
      - å†æ¢
      - ç»§ç»­æ¢
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.nmb.show/xiaojiejie2.php

  - type: url
    rules:
      - èˆ”ç‹—æ—¥è®°
      - èˆ”ç‹—
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://api.oick.cn/dog/api.php

  - type: url
      - è‚¡ç¥¨ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://zyzcfa.com:444/api/stocks?keyword={{1}}

  - type: url
    rules:
      - ç‹è€…(.*)
      - ç‹è€…è£è€€(.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/wzry.php?msg={{1}}

  - type: url
    rules:
      - (.*)å¤©æ°”
      - å¤©æ°”(.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/tq.php?msg={{1}}&n=1

  - type: url
    rules:
      - ping (.*)
      - è¶…çº§ping (.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/sping.php?url={{1}}

  - type: url
    rules:
      - çŸ­ç½‘å€ (.*)
      - çŸ­é“¾æ¥ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: https://www.lzfh.com/api/dwz.php?cb=1&sturl=6&longurl={{1}}
        get: dwz_url       

  - type: url
    rules:
      - æŠ–éŸ³ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: https://api.oick.cn/douyin/api.php?url={{1}}
        get: play
 
  - type: url
    rules:
      - è“å¥äº‘ (.*) (.*)
      - è“å¥äº‘ (.*)
      - è“å¥äº‘ (.*)å¯†ç :(.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: http://yingy.20wl.co/Api/php/LanZous.php?url={{1}}&pwd={{2}}
        get: data.url

  - type: url
    rules:
      - æœ (.*)(.*)
      - çœ‹ (.*) (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/video_so.php?msg={{1}}&max=10&n={{2}}

  - type: url
    rules:
      - åŠ¨æ¼« (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/age.php?msg={{1}}&max=10&n=1

  - type: url
    rules:
      - æ¸¸æˆ
      - å¼€å§‹æ¸¸æˆ
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=å¼€å§‹æ¸¸æˆ

  - type: url
    rules:
      - ç­” (.*)
      - ç­”(.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=ç­”{{1}}

  - type: url
    rules:
      - æç¤º
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://hm.suol.cc/API/game_gs.php?msg=æç¤º

  - type: url
    rules:
      - åƒåœ¾ (.*)
      - åƒåœ¾åˆ†ç±» (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://xiaoapi.cn/api/laji.php?msg={{1}}

  - type: url
    rules:
      - æˆ˜åŠ› (.*)
      - æœ€ä½æˆ˜åŠ› (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://jiuli.xiaoapi.cn/i/wzry_zdzl.php?name={{1}}

  - type: url
    rules:
      - ç™¾ç§‘ (.*)
      - ç™¾åº¦ç™¾ç§‘ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: http://xiaoapi.cn/api/sgbaike.php?msg={{1}}

  - type: url
    rules:
      - (.*)çŸ­è§†é¢‘
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: http://ovooa.com/API/sjsp/api.php?msg={{1}}&type=json
        get: data.url
  - type: url
    rules:
      - å‘½å(.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: http://ovooa.com/API/qzl/api.php?qq=304625534&s=McjKsYNf3M&name={{1}}
        get: text    
  - type: url
    rules:
      - èŠ±çŒ«åŠŸèƒ½
      - èœå•
    request:
        #çº¯æ–‡æœ¬
        response_type: text
        url: https://womc.cn/elm/gn.txt

  - type: url
    rules:
      - å¿«æ‰‹ (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: https://ios.womc.cn/jiexi/?url={{1}}
        get: data.url       
  - type: url
    rules:
      - ç½‘æ˜“äº‘ (.*)	
    request:
        #çº¯æ–‡æœ¬
        response_type: json
        url: https://api.paugram.com/netease/?id={{1}}
        get: link       
  - type: url
    rules:
      - äºŒç»´ç  (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: image
        url: https://api.womc.cn/api/qrcode/api.php?text={{1}}
  - type: url
    rules:
      - æ’•å¼€ (.*)
      - æ’•è£‚ (.*)
      - æ’•äº†ä½  (.*)
      - ç»™æˆ‘æ’•äº† (.*)
    request:
        #çº¯æ–‡æœ¬
        response_type: image
        url: http://ovooa.com/API/si/?QQ={{1}}
  - type: url
    rules:
      - èµ (.*)
      - å¾ˆèµ (.*)
      - (.*) èµå•Š
      - (.*) å¤ªèµäº†
    request:
        #çº¯æ–‡æœ¬
        response_type: image
        url: http://ovooa.com/API/zan/api.php?QQ={{1}}

  - type: url
    rules:
      - ç¿»è¯‘ (.*)
    request:
      response_type: text
      url: http://hm.suol.cc/API/fy.php?msg={{1}}

  - type: url
    rules:
      - æ”¶å½•æŸ¥è¯¢ (.*)
      - ç™¾åº¦æ”¶å½• (.*)
    request:
      response_type: json
      url: https://api.womc.cn/api/shoulu/api.php?domain={{1}}
      get: data
  - type: url
    rules:
      - ^æŸ¥å­—\s*(\S*)$
    replace:
      - 
        - <br>

        - "\n" 
    request:
        response_type: template
        url: https://api.tianapi.com/txapi/xhzd/index?key=19eea766886493ecd04e770d0c2b56f9&word={{1}}
        template: "æ±‰å­—ï¼šgjson(newslist.[0].hanzi)\nè¯»éŸ³ï¼šgjson(newslist.[0].pyyb)\nè§£é‡Šï¼šgjson(newslist.[0].content)\næ‹“å±•ï¼šgjson(newslist.[0].explain)"    
  - type: url
    rules:
      - å¤§ä¸è¢œ
      - ç¾è…¿
    request:
        #å›¾ç‰‡
        response_type: image 
        url: https://api.iyk0.com/mtt
  - type: url
    rules:
      -  ^ä¸¾ç‰Œ (.*)$
    request:
      response_type: image
      url: http://xiaobai.klizi.cn/API/tw/source.php?text={{1}}
  #æ–‡å­—è½¬è¯­éŸ³(å°äº‘ï¼Œå°åˆšï¼Œè‹¥å…®ï¼Œæ€çªï¼Œæ€ä½³ï¼Œæ€è¯šï¼Œè‰¾çªï¼Œçˆ±ä½³ï¼Œè‰¾è¯šï¼Œè‰¾è¾¾ï¼Œå®å„¿ï¼Œç‘ç³)
  - type: url
    rules:
      - (.*)è¯­éŸ³(.*)
    request:
      response_type: json
      url: 'https://jintia.jintias.cn/api/jinyytts.php?msg={{2}}&name={{1}}'
      get: data.tts
  - type: url
    rules:
      - æœæ­Œ (.*)(.*)
      - å¬ (.*) (.*)
    request:
      response_type: text
      url: https://api.womc.cn/api/qqyy/api.php?msg={{1}}&n={{2}}
  - type: url
    rules:
      - é“ƒå£° (.*)
    request:
      response_type: json
      url: http://ovooa.com/API/yydg/api.php?msg= {{1}}&n=1
      get: data.url


  # - type: url
  #   rules:
  #     - .*
  #   request:
  #       #çº¯æ–‡æœ¬
  #       response_type: json
  #       url: https://api.ixiaowai.cn/tgrj/index.php
  #       get: data.msg
